### ISSUE TITLE
Version 3.0.0 does not work with Visual Studio 2017

### ISSUE THREAD

**Issue by Molinarius** [lkytal/SmoothScroll#22]
The version 3.0.0 does not work any more with Visual Studio 2017.

When opening a file, this error message is displayed:

    ---------------------------
    Microsoft Visual Studio
    ---------------------------
    The 'SmoothScrollPackage' package did not load correctly.

    The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\...\AppData\Roaming\Microsoft\VisualStudio\15.0_d1378007\ActivityLog.xml'.

    Restarting Visual Studio could help resolve this issue.

    Continue to show this error message?
    ---------------------------
    Yes   No   
    ---------------------------

`ActivityLog.xml` contains this entry:

    <entry>
      <record>2295</record>
      <time>2019/05/10 10:45:53.473</time>
      <type>Error</type>
      <source>VisualStudio</source>
      <description>CreateInstance failed for package [SmoothScrollPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
      <guid>{6BB22343-DF63-4F19-8088-66CAEAFDE0AD}</guid>
      <hr>80004005 - E_FAIL</hr>
      <errorinfo></errorinfo>
    </entry>

On my computer, the file `Microsoft.VisualStudio.Shell.15.0.dll` has version 15.0.28307.539, but not 16.

I currently don’t have Visual Studio 2019 installed.

**Comment by Ghost4Man** [comment]
I have the same problem (probably after an automatic update), here's the [error message with Fusion log enabled](https://gist.githubusercontent.com/Ghost4Man/445bfb16a9c55053ee1eb54308a56b62/raw/d2bcc82ffed78e1cf8f0d6fedf793d4dc39c1b46/SmoothScrollPackage_FusionLog.txt).

**Comment by lkytal** [comment]
Restored backward support to VS2017, please update to v3.1.0

**Comment by MagicAndre1981** [comment]
3.1.0 can't be installed, because `Microsoft.VisualStudio.MPF.12.0` is missing:

![image](https://user-images.githubusercontent.com/8274816/57598020-dd78e800-7551-11e9-821a-5df5b7d0efa2.png)

**Comment by lkytal** [comment]
> 
> 
> 3.1.0 can't be installed, because `Microsoft.VisualStudio.MPF.12.0` is missing:
> 
> ![image](https://user-images.githubusercontent.com/8274816/57598020-dd78e800-7551-11e9-821a-5df5b7d0efa2.png)

What's your VS version?

**Comment by MagicAndre1981** [comment]
I use VS2017 15.9.11

[according to Microsoft](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/) this entry is obsolete for a while:

> If you have a dependency on Microsoft.VisualStudio.MPF then delete it. This dependency is a legacy one that hasn’t been needed since before Visual Studio 2010.

**Comment by lkytal** [comment]
> 
> 
> I use VS2017 15.9.11
> 
> [according to Microsoft](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/) this entry is obsolete for a while:
> 
> > If you have a dependency on Microsoft.VisualStudio.MPF then delete it. This dependency is a legacy one that hasn’t been needed since before Visual Studio 2010.

I've just uploaded version v3.1.1, please take a try.

**Comment by chviladislav** [comment]
I have the same issues, so I tried the 3.1.1. I'm able to install it now, but after run I got this message (copied from C:\Users\xxxx\AppData\Roaming\Microsoft\VisualStudio\15.0_dec70ffa\ActivityLog.xml):

<description>SetSite failed for package [SmoothScrollPackage]Source: &apos;Microsoft.VisualStudio.Shell.15.0&apos; Description: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.&#x000D;&#x000A;System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.PackageContainer.GetService(Type serviceType)&#x000D;&#x000A;   at System.ComponentModel.Container.Site.GetService(Type service)&#x000D;&#x000A;   at System.ComponentModel.Component.GetService(Type service)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.get_SettingsManager()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingsFromStorage()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.set_Site(ISite value)&#x000D;&#x000A;   at System.ComponentModel.Container.Add(IComponent component, String name)&#x000D;&#x000A;   at System.ComponentModel.Container.Add(IComponent component)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.GetDialogPage(Type dialogPageType)&#x000D;&#x000A;   at SmoothScroll.SmoothScrollPackage.&lt;InitializeAsync&gt;d__2.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass17_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>

**Comment by lkytal** [comment]
I noticed this risk but it does not happen at VS2019. I've uploaded v3.1.2 with a potential workaround.

**Comment by MagicAndre1981** [comment]
3.1.2 can be installed in 2017, but still causes the error from @chviladislav

> SetSite failed for package [SmoothScrollPackage]Source: 'Microsoft.VisualStudio.Shell.15.0' Description: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.

**Comment by lkytal** [comment]
Well, let's try v3.1.3...

**Comment by MagicAndre1981** [comment]
nope, still error:

![image](https://user-images.githubusercontent.com/8274816/57601723-94c72c00-755d-11e9-9c4c-73bb5630552e.png)

> Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.

**Comment by MagicAndre1981** [comment]
have you tried to call `await this.JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);` before init of SettingsPage?

**Comment by MagicAndre1981** [comment]
ok, you added it. I saw it in Decompiler.

if nothing helps, create 2 extension in 2 different branches. 

**SmoothScroll**, based on AsyncPackage for VS >=2019
**SmoothScrollLegacy** based on commit before change to async to support older VS versions up to 2017.

**Comment by MagicAndre1981** [comment]
I searched a bit in the extension of Mads Kristensen and he only calls `OptionsPage = base.GetDialogPage(typeof(OptionsPage)) as OptionsPage;` like you did before the async migration. So do this again.

https://github.com/madskristensen/JavaScriptPrettier/blob/master/src/PrettierPackage.cs#L35
https://github.com/madskristensen/WebAccessibilityChecker/blob/master/src/VSPackage.cs#L45

**Comment by VaheHovh** [comment]
v3.1.3 doesn't work with VS 2017.

SetSite failed for package [SmoothScrollPackage]Source: &apos;Microsoft.VisualStudio.Shell.15.0&apos; Description: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.&#x000D;&#x000A;System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.PackageContainer.GetService(Type serviceType)&#x000D;&#x000A;   at System.ComponentModel.Container.Site.GetService(Type service)&#x000D;&#x000A;   at System.ComponentModel.Component.GetService(Type service)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.get_SettingsManager()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingsFromStorage()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.set_Site(ISite value)&#x000D;&#x000A;   at System.ComponentModel.Container.Add(IComponent component, String name)&#x000D;&#x000A;   at System.ComponentModel.Container.Add(IComponent component)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.GetDialogPage(Type dialogPageType)&#x000D;&#x000A;   at SmoothScroll.SmoothScrollPackage.&lt;InitializeAsync&gt;b__2_0()&#x000D;&#x000A;   at System.Threading.Tasks.Task`1.InnerInvoke()&#x000D;&#x000A;   at System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at SmoothScroll.SmoothScrollPackage.&lt;InitializeAsync&gt;d__2.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass17_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__78.MoveNext()

**Comment by MagicAndre1981** [comment]
@VaheHovh

the extension itself works, I see the different scrolling, but option page loading fails.

**Comment by lkytal** [comment]
Finally, I believe that v3.1.4 solved this problem.

**Comment by MagicAndre1981** [comment]
yes, removing the Task stuff around option page call fixes it for me, extension loads and option page shows up:

![image](https://user-images.githubusercontent.com/8274816/57672146-25157780-7617-11e9-83d9-75e025ca4df4.png)
